# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_page_showPage:
    pattern: /{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.page:showPageAction
        _sylius:
            template: SyliusWebBundle:Frontend/Page:show.html.twig
            method: findPage
            arguments: [$id]
    requirements:
        id: ".+"
