# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_backend_product_attribute_value_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.product_attribute_value:deleteAction
        _sylius:
            template: SyliusWebBundle:Backend/Misc:delete.html.twig
            redirect:
                route: sylius_backend_product_show
                parameters: {'id': $productId}